on: push

jobs:
  set-environment-variables:
    strategy:
      matrix:
        os: ['windows-latest','ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set Variable on Ubuntu
      if: runner.os == 'Linux'
      run: |
        export name=Siddharth
        echo $name
        
    - name: Set Variable on Windows
    #  if: runner.os == 'Windows'
      run: |
        Set-Variable -Name "name" -Value "KodeKloud"
        echo $name

  reports:
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Upload Report to AWS S3
      run: echo "Uploading reports .. .. .. .. ."
        
